### PR TITLE
feat(stop_accel_evaluator): use flexible lpf

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## PR Type

- Improvement

## Description

To align with https://github.com/autowarefoundation/autoware.universe/pull/1135

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/l/c/X1p69s6B
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yabuta** [comment]
@takayuki5168 
Change looks good.
Do you know why the build-and-test-differential / build-and-test-differential (galactic) (pull_request) error is happening?

**Review by yabuta — APPROVED** [review]
LGTM

**Comment by takayuki5168** [comment]
@yabuta 
Do you know why pre-commit, which is required to merge this PR, was skipped? This happens in another PR.
I'm not sure, but github actions setting of pre-commit may be incorrect?

image

**Comment by yabuta** [comment]
Sorry, I dont know.
Perhaps, Change is too shorts?

**Comment by takayuki5168** [comment]
@yabuta Sorry, I thought the skipped pre-commit has to pass in order to merge this PR.
Please merge the PR when you want to.

**Pull request merged**
