### PR TITLE
feat: change ros2_numpy branch in repos to humble

### PR DESCRIPTION
**Pull request by yabuta**
## Description

It is nessesary this change for humble.
https://github.com/Box-Robotics/ros2_numpy/commit/9bb21a13eaa2f8084cef797539629ab8d806c44b

So I fix ros2_numpy branch to humble.

## Tests performed

- vcs import at humble.
- rosdep install and build
  - rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
  - colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
In the previous private repository this change was already merged into the humble branch, so maybe we can skip this review?

```
 vendor/ros2_numpy:
    type: git
    url: git@github.com:Box-Robotics/ros2_numpy.git
    version: humble
```

Otherwise I will do it tomorrow when I have access to a PC with humble

**Comment by yabuta** [comment]
@knzo25 
You are right.
Same Change is merged in this PR.
https://github.com/tier4/calibration_tools.iv/pull/157/files

Please approve.

**Comment by knzo25** [comment]
I thnk this .repos is till different than the one from the private repostory (shouldn't we avoid pasting private links in public repositories?)

For example, we need to use the humble version of lidartag

```
  vendor/lidartag:
    type: git
    url: git@github.com:tier4/LiDARTag.git
    version: humble
```

**Comment by yabuta** [comment]
We need more change.
Maybe it is better to sync pilot-auto calibration_tools.repos.
https://github.com/tier4/pilot-auto/pull/498

**Pull request closed without merging**
