### PR TITLE
feat(lidar-lidar-calib):  add sensor model aip x1 1

### PR DESCRIPTION
**Pull request by YoheiMishina**
## Description
Add a launcher corresponding to the sensor model 'aip_x1_1' added to x1.

## Related links
https://tier4.atlassian.net/browse/AEAP-91

## Tests performed
Using an actual vehicle, we confirmed that the accuracy is equivalent to 'aip_x1'.
Screenshot from 2023-05-31 13-55-53

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
Is this normal?
246040693-54e79b8b-ddf2-4a1f-b136-933f0d81ea14

**Comment by h-ohta** [comment]
@YoheiMishina Could you fix PR title?

**Comment by YoheiMishina** [comment]
> Is this normal? 246040693-54e79b8b-ddf2-4a1f-b136-933f0d81ea14

Yes. Because Green points is before calibration. Light blue points is after calibration.

**Comment by aohsato** [comment]
@YoheiMishina @h-ohta I think the changes look good.
Is the `sensor_model` naminig `aip_x1_1` already decided? How do you plan to change `aip_launcher` and related repositories?

**Comment by YoheiMishina** [comment]
@aohsato 
> @YoheiMishina @h-ohta I think the changes look good. Is the `sensor_model` naminig `aip_x1_1` already decided? How do you plan to change `aip_launcher` and related repositories?

That naming was agreed in eve project. We have also merged the sensor model into aip_launch.x1.eve.
We have not decided how to publish it as a reference model for x1.
https://github.com/tier4/aip_launcher.x1.eve/commit/25f6b0f744117008791493f8e0a3736c084b8f85

**Comment by aohsato** [comment]
@YoheiMishina I understood, thanks.

@h-ohta I have no problem with this merge.

**Review by yabuta — APPROVED** [review]

**Review by h-ohta — APPROVED** [review]

**Pull request merged**
