### PR TITLE
fix(extrinsic_calibration_manager): rename tag-based camera topic for xx1 

### PR DESCRIPTION
**Pull request by muraki-t4**
## Description

Rename tag-based camera topic for xx1

## Related links

None

## Tests performed

Launched extrinsic tag-based calibration and confirmed that calibration has been successfull.

## Notes for reviewers

None

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by yabuta — DISMISSED** [review]
LGTM

**Comment by knzo25** [comment]
Dont merge this
We need to use image raws for cameras with distortion

**Comment by muraki-t4** [comment]
@knzo25 
Does this mean that the topics are different for cameras with and without distortion?
If so, should I change the topic in the launch file to switch by the additional `distortion` argument?

**Comment by knzo25** [comment]
The camera info topic contains both the data for distorted  (image_raw) and undistorted (image_rect) images.
The tools in the main branch assumes the incoming images are distorted and uses the camera_info accordingly.
The "exception" to this are some of the C1/C2 cameras used currently in our projects since they can effectively undistort the images before entering the ROS pipeline (it is done in their ISP).

If you want to calibrate XX1 (besides the  vehicle_id=4), you need to record the image_raw topics.

Btw: the new version accommodates for this situation and can switch between using image_raw and image_rect with a flag (though untested since we don't have the data to test it and does not form part of our requirements so far)

This issue may give you some idea of what would happen were you to ignore the differences (not exactly the same but still related to the difference between images)
https://github.com/tier4/CalibrationTools/issues/137

**Comment by knzo25** [comment]
@muraki-t4 
What are you planning do to with this PR?
Turn it into a draft? Close it?

**Comment by muraki-t4** [comment]
@knzo25 
Sorry, for my late response.
I will close this pr.

I will change the launch files locally until new version is released.

**Pull request closed without merging**
