### PR TITLE
fix:(extrinsic_tag_based_calibrator): Fixed the apriltag version

### PR DESCRIPTION
**Pull request by knzo25**
## Description
Fixed the apriltag_version since the API is unstable right now, and the newest commit required an unavailable library in galactic
We can move to the latest branch/tag when we migrate to humble

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
@yabuta 
Last time we also added the .repos file in the X2 and XX1 repositories, so we need to make a PR again (Can I do PRs there, or is it necessary for you do to it?)

**Comment by yabuta** [comment]
@knzo25 
I would like to remove pilot-auto.xx1 and pilot-auto.x2 calibration.repos and install them according to the README in this repository, so no need to update them.
However, X1 has an apriltag in autoware.repos  for OTA, so it may be necessary to modify this one.
https://github.com/tier4/pilot-auto.x1.eva/blob/tier4/universe/autoware.repos#L154

Please make PR?

**Review by yabuta — APPROVED** [review]
LGTM

**Comment by knzo25** [comment]
@yabuta 
I also fixed the version of the msges.
I made the PR for the X1. Did you mean to make the PR deleting the calibration .repos for all the projects?

**Pull request merged**
