### PR TITLE
fix: ground_plane calibrator compatibility for humble

### PR DESCRIPTION
**Pull request by knzo25**
## Description
The headers changed between galactic and humble and since the ground based calibrator was developed before the branch for humble it lacked the compatibility fix

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
@yabuta 

I also fixed some spelling errors from my part.
Since this PR is for humble, should I create another PR for the tier4/universe branch?

(also, since this is a public repository, is english the default language right?)

**Review by yabuta — CHANGES_REQUESTED** [review]
There is #include <tf2_eigen/tf2_eigen.h> in extrinsic_ground_plane_calibrator.cpp.
Please Change this file too.

**Comment by yabuta** [comment]
@knzo25 It is nessesary that the PR is for tier4/universe(galactic).
I think it would be a good idea to merge it into tier4/universe(galactic) and then submit a PR to sync tier4/universe to the humble branch.

(also, since this is a public repository, is english the default language right?)
Yes.

**Comment by yabuta** [comment]
@knzo25 
I think it is good for your change.
But I get below error.
```
--- stderr: extrinsic_ground_plane_calibrator                               
/home/yabuta/workspace/pilot-auto/src/autoware/calibration_tools/sensor/extrinsic_ground_plane_calibrator/src/extrinsic_ground_plane_calibrator.cpp:31:10: fatal error: tf2_eigen/tf2_eigen.hpp: No such file or directory
   31 | #include <tf2_eigen/tf2_eigen.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/extrinsic_ground_plane_calibrator.dir/build.make:76: CMakeFiles/extrinsic_ground_plane_calibrator.dir/src/extrinsic_ground_plane_calibrator.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/extrinsic_ground_plane_calibrator.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
```

I'm looking into it some more.

**Comment by knzo25** [comment]
@yabuta 
The latest commit should fix that.
I currently can not reproduce it locally as I don't have a humble environment at home (so I am looking at the github checks :sweat_smile: )

**Comment by yabuta** [comment]
@knzo25 It works.Thanks.

The PR to tier4/universe is not nessesary.
I check other files, there is not same change.
So this PR is OK and Let's merge.
https://github.com/tier4/CalibrationTools/blob/a8ad0d14de4efd5bf2c743b6669dd02fe77f0d85/sensor/extrinsic_tag_based_calibrator/src/extrinsic_tag_based_calibrator.cpp#L26

**Review by yabuta — APPROVED** [review]

**Pull request merged**
