### PR TITLE
fix(deviation_estimator): fix stddev estimation equation + refactor

### PR DESCRIPTION
**Pull request by kminoda**
Signed-off-by: kminoda <koji.minoda@tier4.jp>

## Description
Validation: https://tier4.atlassian.net/browse/T4PB-23658 (internal link)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by YamatoAndo — APPROVED** [review]

**Comment by kminoda** [comment]
@YamatoAndo @yabuta 
Can you push `squash and merge` button in this PR? (I cannot push it even though all the CI passes :cry: )

**Comment by YamatoAndo** [comment]
Neither can I.
Screenshot from 2022-11-24 15-20-05

**Comment by YamatoAndo** [comment]
@kminoda How about trying "Update with rebase"?

**Comment by kminoda** [comment]
I merged main instead of rebase (it said that there're some conflicts)

**Comment by kminoda** [comment]
Success!!

**Pull request merged**
