### PR TITLE
feat: move localization, vehicle, and control tools to the autoware_tools repository

### PR DESCRIPTION
**Pull request by yabuta**
## Description

Follow [This discussion](https://github.com/tier4/CalibrationTools/discussions/157), I move localization, vehicle, control tool to [autoware_tools](https://github.com/autowarefoundation/autoware_tools)

In this PR, I remove these tools and msg.

[autoware_tools PR](https://github.com/autowarefoundation/autoware_tools/pull/22)

I checked colcon build is success and sensor calibration launch test.
I launched below command and I tested some calibration tools
 ex) LiDAR - Camera

```
ros2 run sensor_calibration_manager sensor_calibration_manager
```

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by knzo25 — APPROVED** [review]
LGTM <3

**Review by SakodaShintaro — APPROVED** [review]
Looks Good To Me

**Comment by yabuta** [comment]
I will merge this PR when Mitsudome-san Approves [this PR](https://github.com/autowarefoundation/autoware_tools/pull/22).

**Comment by yabuta** [comment]
I will merge this PR first as [this PR](https://github.com/autowarefoundation/autoware_tools/pull/22) may take some time for spell check, etc.

**Pull request merged**
