### PR TITLE
feat(intrinsic_camera_calibrator): cherrypick the new intrinsics calibrator into the galactic branch

### PR DESCRIPTION
**Pull request by knzo25**
* Partial implementation of the new intrinsic camera calibrator

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Improved the data selection for bigger boards somewhat similar to the image pipeline

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Implemented all up until the calibration. Need to implement other sources, views, and I/O

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Added interface to load rosbags directly

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Implemented missing views and fixed some bugs (views: unrectified, rectifies, training, and evaluation)

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Removed debug code

* Added the copyright notice Added a simple launcher with the corresponding cfg file Implemented save functionalities
Added docstring documentation
Removed some debug info

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed several bugs and added the image file source interface

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed the ruamel versin in the package xml

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Implemented the chess board detector and commented out unimplemented features

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Implemented calibration through apriltag arrays

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed some typos

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Implemented the evaluation mode and initial intrinsics loading

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Implemented a fast calibration routine that is cointinuously executed during the main calibration process. This is due to the fact that some of the data collection criteria use the intrinsics to obtain 3d information

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed small errors and cosmestic changes

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed some bugs and applied some suggestions from the code review

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed argument format

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Added documentation for the new intrinsic camera calibrator

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Attempted to center the images

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* New attempt

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Yet again

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Yet again

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Now the caption is not centered

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Forgot the extension change

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed the enbaled state of the calibration and evaluation buttons when no data was yet available Also added references to the documentation

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed more details in the documentation

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed the pause/resume functionality in sources other than topics. Implemented one change from the PR

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed a lot of typos

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed more typos

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

* Fixed tests

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

---------

Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
@yabuta 
Do you know why the following package gives an error?
`<test_depend>ament_copyright</test_depend>`

`intrinsic_camera_calibrator: Cannot locate rosdep definition for [ament_copyright]`

**Comment by yabuta** [comment]
@knzo25 Sorry, I dont know. Only humble package?

**Comment by knzo25** [comment]
ci/cd changed a little so I had to change one part of the code.
Additionally, test-related packages were not found although they exist in galactic.
Not knowing what else I could do I removed them in the meantime

**Review by aohsato — APPROVED** [review]
LGTM

**Pull request merged**
