### PR TITLE
fix(extrinsic_reflector_based_calibrator): remove old header

### PR DESCRIPTION
**Pull request by mebasoglu**
## Description

`extrinsic_reflector_based_calibrator` package cannot be built. It has a header file which causes compile error:
https://github.com/tier4/CalibrationTools/blob/e0a021960e8f7bfc9522bde0cc97fafdf09f693d/sensor/extrinsic_reflector_based_calibrator/src/extrinsic_reflector_based_calibrator.cpp#L16

```
Starting >>> extrinsic_reflector_based_calibrator
--- stderr: extrinsic_reflector_based_calibrator
/home/dell/projects/autoware.robicarr/src/autoware/calibration_tools/sensor/extrinsic_reflector_based_calibrator/src/extrinsic_reflector_based_calibrator.cpp:16:10: fatal error: tier4_autoware_utils/tier4_autoware_utils.hpp: No such file or directory
   16 | #include <tier4_autoware_utils/tier4_autoware_utils.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This header file was removed with this PR: https://github.com/autowarefoundation/autoware.universe/pull/5027

When I delete the header and try to build the project, it successfully compiles.

## Related links

The PR which the header file was removed: https://github.com/autowarefoundation/autoware.universe/pull/5027

## Tests performed

I tested to build it inside a fresh Autoware workspace and it was built successfully.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by knzo25 — APPROVED** [review]
Thanks for the catch ! LGTM

**Comment by knzo25** [comment]
@mebasoglu 
I believe we have an informal policy of PRs being merged by the person who sent it. Could you please press the "Squash and merge" button? :pray:  (otherwise I will be merging it in a week or so)

**Comment by mebasoglu** [comment]
Hello @knzo25 , I don' t have write access to the repo so I am not able to merge the PR.

**Comment by knzo25** [comment]
Apologies, I am not aware of the repository's permissions  :bow: 
I will merge this right away then

**Pull request merged**
