### PR TITLE
feat(extrinsic_mapping_based_calibrator): initial release

### PR DESCRIPTION
**Pull request by knzo25**
## Description
This PR implements a new calibration method for lidar-lidar (in the future we will implement also camera-lidar) based on a mapping - matching pipeline.

In particular, this PR implements the following
 - Mapping using a single lidar using NDT
 - Map construction, pose interpolation and related helper functions
 - Kidnapped robot / mapping errors handling
 - Calibration frame (data) selection to minimize interpolation errors and maximize the information needed for calibration
 - Naive single-frame calibration (single lidar scan against the constructed map).
 - Joint multi-frame calibration (multiple lidar scans optimized jointly against the constructed map).
 - Calibration API compliance.
 - Calibration is performed in paralell

*Note: we need to use the autoware.universe from this PR: https://github.com/autowarefoundation/autoware.universe/pull/1754
to use the new voxel grid filter and the fixed JointICP implementation.
If the universe version of that PR can not be used due to incompatibilities or becoming old, it suffices with checking out the `tier4_pcl_extensions` package with the following command: `git checkout main && git checkout feature/calibration_pcl_extensions sensing/tier4_pcl_extensions`.

## Related links
None

## Tests performed

Using an `XX1` environment, run the following command:

```
ros2 launch extrinsic_calibration_manager calibration.launch.xml mode:=mapping_based sensor_model:=aip_xx1 vehicle_model:=$VEHICLEMODEL logging_simulator:=false
```

Then in another terminal run the logging simulator (they can be launcher together, but it better to launch them separately for visibility).

After both calibrator and logging simulator and running, play the provided rosbag with a low playback speed (we need this because otherwise some pointclouds are dropped in the sensing pipeline)

```
ros2 bag play . -r 0.1
```

Once the rosbag ends, run the calibration (manually) via the following command:

```
ros2 service call /stop_mapping std_srvs/srv/Empty {}
```

After the calibration finishes (it may take a few minutes), the initial and calibrated pointclouds should be displayed in rviz.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
@drwnz 
This is the "updated" PR for the mapping tool.
(The old one was https://github.com/tier4/CalibrationTools/pull/23)

**Comment by drwnz** [comment]
@knzo25 thank you, can you take a look into the conflict please?

**Comment by knzo25** [comment]
@drwnz 
Rather than a real conflict there were new tools in both branches :laughing:

**Comment by knzo25** [comment]
@yabuta 

The tests in the CI/CD are failing due to coding conventions.

I applied the changes suggested by `crustify` locally, but then `pre-commit` turns them back, so using the current development flow the test will simply not pass.

Which is correct here? `crustify`? `pre-commit`?

**Comment by knzo25** [comment]
After reading our internal slack, it seems we are dropping `crustify` and instead relying on clang's lint.

**Comment by yabuta** [comment]
@knzo25 Yes.  `crustify` is not used already. Please use `pre-commit`.

**Review by drwnz — APPROVED** [review]
LGTM!
- Tested operation on XX1 and X2, works well and also passing required CI/CD.
Great work :)

**Pull request merged**
